### ISSUE TITLE
Error: Compilation failed.

### ISSUE THREAD

**Issue by MetaMmodern** [NickNevzorov/dart_thread#1]
## Description

Hello and thank you for this beautiful library! Unfortunately I couldn't make it work for web yet. 

When I follow the instructions I run this command:
`dart compile js -O2 -o 'web/TestThread.dart.js' 'lib/controllers/TestThread.dart'` (my TestThread.dart is in controllers folder, all files are below)

and I get a very very long log and this error: 

![image](https://github.com/NickNevzorov/dart_thread/assets/42899786/cfcb5638-3719-4a50-a897-2425feeadf9e)

`Error: Compilation failed`

Notice, that when I run `dart compile js --help` it doesn't give me a --libraries-spec flag:

![image](https://github.com/NickNevzorov/dart_thread/assets/42899786/8270ae6d-dce6-4cc4-a086-341fd959ce7d)

Please help me build the worker, thank you.

## Files

<details>
<summary>lib/controllers/TestThread.dart</summary>

```dart
@JS()

import 'dart:html';
import 'dart:js_interop';
import 'tdlib_controller.dart';

@JS('self')
external DedicatedWorkerGlobalScope get self;

void main() async {
  await TestThread().main(self);
}
```
</details>

<details>
<summary>lib/controllers/tdlib_controller.dart</summary>

```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:isolate';
import 'dart:math' show Random;

import 'package:flutter/foundation.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:minimalistic_telegram/stores/event_emitter.dart';
import 'package:palestine_console/palestine_console.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:path_provider/path_provider.dart';
import 'package:synchronized/synchronized.dart';
import 'package:dart_thread/dart_thread.dart';

import 'package:tdlib/tdlib.dart';
import 'package:tdlib/td_api.dart' as td_api;

int _random() => Random().nextInt(10000000);

class TestThread extends DartThread {
  // Need to mapping Class to super.init,
  // because dart did not allow override a static method
  static TestThread newInstance() => TestThread();

  @override
  // Running once in isolate or worker
  Future<void> onExecute(Function(dynamic message) sendMessage) async {
    TdNativePlugin.registerWith();
    final tdlibPath = kIsWeb
        ? null
        : (Platform.isAndroid || Platform.isLinux || Platform.isWindows)
            ? 'libtdjson.so'
            : null;

    await TdPlugin.initialize(tdlibPath);

    //var x = _rawClient.td_json_client_create();
    while (true) {
      final s = TdPlugin.instance.tdReceive();
      if (s != null) {
        sendMessage(s);
      }
    }
  }
}

// more unrelated code is below
```
</details>

## Env

dart --version: Dart SDK version: 2.18.7 (stable) (Thu Jan 12 10:44:08 2023 +0000) on "macos_x64"

flutter --version: Flutter 3.13.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12fccda598 (9 weeks ago) • 2023-09-19 13:56:11 -0700
Engine • revision bd986c5ed2
Tools • Dart 3.1.2 • DevTools 2.25.0

**Comment by NickNevzorov** [comment]
Hi!

I don't know how this is possible, but you have a very old version of dart. 
For you version flutter on macos should be dart 3.1.2
https://docs.flutter.dev/release/archive?tab=macos

Try to reinstall sdk

p.s. my software:

dart --version 

`Dart SDK version: 3.1.5 (stable) (Tue Oct 24 04:57:17 2023 +0000) on "windows_x64"`

flutter --version

```
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (4 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0

```

**Comment by MetaMmodern** [comment]
@NickNevzorov thanks! I'm using fvm for managing flutter versions, chances are when I use the build it uses fvm but alongside old dart is installed. I'll give it a try through fvm and will let know

**Comment by MetaMmodern** [comment]
Yes, that was the issue, not using correct dart version.
Thanks! I'm closing the issue.
