### ISSUE TITLE
Error when deploying for the web

### ISSUE THREAD

**Issue by devfelipereis** [NickNevzorov/dart_thread#3]
Hello!

I was testing your lib and seens to work fine in dev. Now I'm trying to make it work for the web in production mode but is not working.

I got this in the console:

`
No enum value matches 'inified:ajq', did you use the correct mode or case-style or forgot to specify a default value?`

Looks like a error with the minified version, do you have any idea on how to fix this? Thank you!

**Comment by NickNevzorov** [comment]
flutter --version ?

**Comment by NickNevzorov** [comment]
```
Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 54e66469a9 (4 weeks ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186                                             
Tools • Dart 3.3.4 • DevTools 2.31.1  

```
Example working fine on this last version

**Comment by devfelipereis** [comment]
```
Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (4 weeks ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1
```

I'm using the **messageToObject** method to call Class.fromJson. In the **sendMessage** I'm calling `sendMessage(json.encode(map))`.

**Comment by devfelipereis** [comment]
Hey, looks like a problem on my side. Sorry.
